---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Insert passwords from secrets
  commands:
  - cat other_settings.py
  - sh replacepasswords.sh
  - cat other_settings.py
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

    DRONE_SA_USERNAME:
      from_secret: DRONE_SA_USERNAME
    DRONE_SA_PASSWORD:
      from_secret: DRONE_SA_PASSWORD
    DRONE_SECRET_KEY:
      from_secret: DRONE_SECRET_KEY
    DRONE_NEXT_PASSWORD:
      from_secret: DRONE_NEXT_PASSWORD
    DRONE_DATABASE_USERNAME:
      from_secret: DRONE_DATABASE_USERNAME
    DRONE_DATABASE_PASSWORD:
      from_secret: DRONE_DATABASE_PASSWORD
    DRONE_DATABASE_HOST:
      from_secret: DRONE_DATABASE_HOST
#- name: Build gbs.fm Web Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-web:latest -f Dockerfile.gbsfm-web .
#- name: Push gbs.fm Web Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-web:latest
#- name: Build gbs.fm FTP Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-ftp:latest -f Dockerfile.gbsfm-web .
#- name: Push gbs.fm FTP Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-ftp:latest
#- name: Build IRC-bot Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-ircbot:latest -f Dockerfile.gbsfm-ircbot .
#- name: Push IRC-bot Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-ircbot:latest
#node:
#  docker4: 1
