---
kind: pipeline
#type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
steps:
- name: Build and push docker image for GBS.fm Web
  image: plugins/docker
  environment:
    DRONE_DATABASE_HOST:
      from_secret: DRONE_DATABASE_HOST
  settings:
    repo: registry.hemma.lokal/images/gbsfm-web
    tags: latest
    registry: registry.hemma.lokal
    dockerfile: Dockerfile.gbsfm-web




#- name: Insert passwords
#  commands:
#  - git clone https://git.hemma.lokal/scuttle/secrets.git
#  - cp secrets/other_settings.py other_settings.py
#  - sed -i "s/username:password/`cat secrets/listeners.sh.secret`/g" scripts/listeners.sh
#  - sed -i "s/username:password/`cat secrets/metadataupdater.sh.secret`/g" scripts/metadataupdater.sh
#  - sed -i "s/userid=XXX&key=YYY/`cat secrets/metadataupdater.sh.secret2`/g" scripts/metadataupdater.sh
#- name: Build gbs.fm Web Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-web:latest -f Dockerfile.gbsfm-web .
#- name: Push gbs.fm Web Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-web:latest
#- name: Build gbs.fm FTP Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-ftp:latest -f Dockerfile.gbsfm-web .
#- name: Push gbs.fm FTP Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-ftp:latest
#- name: Build IRC-bot Dockerimage
#  commands:
#  - docker build --no-cache -t registry.hemma.lokal/images/gbsfm-ircbot:latest -f Dockerfile.gbsfm-ircbot .
#- name: Push IRC-bot Dockerimage
#  commands:
#  - docker push registry.hemma.lokal/images/gbsfm-ircbot:latest
#node:
#  docker4: 1
